-- Bookings created after a successful payment.
CREATE TABLE IF NOT EXISTS bookings (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    booking_reference VARCHAR(50) NOT NULL UNIQUE,
    user_id BIGINT,
    booking_type VARCHAR(30) NOT NULL,
    status VARCHAR(30) NOT NULL DEFAULT 'confirmed',
    payment_status VARCHAR(30) NOT NULL DEFAULT 'paid',
    payment_gateway VARCHAR(40),
    payment_reference VARCHAR(100),
    payment_amount DECIMAL(12, 2) NOT NULL DEFAULT 0,
    currency VARCHAR(10) NOT NULL DEFAULT 'INR',
    lead_first_name VARCHAR(120),
    lead_last_name VARCHAR(120),
    lead_email VARCHAR(190),
    lead_mobile VARCHAR(30),
    product_title VARCHAR(255),
    product_code VARCHAR(100),
    check_in_date DATE,
    check_out_date DATE,
    travel_date DATE,
    total_travellers INT DEFAULT 1,
    total_adults INT DEFAULT 1,
    total_children INT DEFAULT 0,
    details JSON,
    voucher_path VARCHAR(500),
    voucher_generated_at DATETIME,
    admin_notes TEXT,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    CONSTRAINT fk_bookings_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE SET NULL,
    INDEX idx_bookings_user (user_id),
    INDEX idx_bookings_type (booking_type),
    INDEX idx_bookings_status (status),
    INDEX idx_bookings_created (created_at)
);
